export const SAMPLE_TEST = "SAMPLE_TEST";
export const FETCH_RESOURCES_BY_NAMESPACE_SUCCESS =
  "FETCH_RESOURCES_BY_NAMESPACE_SUCCESS";
export const FETCH_RESOURCES_BY_NAMESPACE_ERROR =
  "FETCH_RESOURCES_BY_NAMESPACE_ERROR";
export const FETCH_RESOURCES_BY_NAMESPACE_LOADING =
  "FETCH_RESOURCES_BY_NAMESPACE_LOADING";
