export const SAMPLE_TEST = 'SAMPLE_TEST';
export const FETCH_RESOURCES_BY_NAMESPACE_SUCCESS = 'FETCH_RESOURCES_BY_NAMESPACE_SUCCESS';
export const FETCH_RESOURCES_BY_NAMESPACE_ERROR = 'FETCH_RESOURCES_BY_NAMESPACE_ERROR';
export const FETCH_RESOURCES_BY_NAMESPACE_LOADING = 'FETCH_RESOURCES_BY_NAMESPACE_LOADING';
export const CREATE_RESOURCE_SUCCESS = 'CREATE_RESOURCE_SUCCESS';
export const CREATE_RESOURCE_ERROR = 'CREATE_RESOURCE_ERROR';
export const CREATE_RESOURCE_LOADING = 'CREATE_RESOURCE_LOADING';
export const FETCH_RESOURCES_BY_USER_ID_LOADING = 'FETCH_RESOURCES_BY_USER_ID_LOADING';
export const FETCH_RESOURCES_BY_USER_ID_SUCCESS = 'FETCH_RESOURCES_BY_USER_ID_SUCCESS';
export const FETCH_RESOURCES_BY_USER_ID_ERROR = 'FETCH_RESOURCES_BY_USER_ID_ERROR';
export const UPDATE_RESOURCE_BY_USER_ID_LOADING = 'UPDATE_RESOURCE_BY_USER_ID_LOADING';
export const UPDATE_RESOURCE_BY_USER_ID_ERROR = 'UPDATE_RESOURCE_BY_USER_ID_ERROR';
export const UPDATE_RESOURCE_BY_USER_ID_SUCCESS = 'UPDATE_RESOURCE_BY_USER_ID_SUCCESS';
export const FETCH_USERS_BY_SEARCH_STRING_LOADING = 'FETCH_USERS_BY_SEARCH_STRING_LOADING';
export const FETCH_USERS_BY_SEARCH_STRING_ERROR = 'FETCH_USERS_BY_SEARCH_STRING_ERROR';
export const FETCH_USERS_BY_SEARCH_STRING_SUCCESS = 'FETCH_USERS_BY_SEARCH_STRING_SUCCESS';
export const SEND_CONNECTION_REQUEST_LOADING = 'SEND_CONNECTION_REQUEST_LOADING';
export const SEND_CONNECTION_REQUEST_SUCCESS = 'SEND_CONNECTION_REQUEST_SUCCESS';
export const SEND_CONNECTION_REQUEST_ERROR = 'SEND_CONNECTION_REQUEST_ERROR';
export const SET_BLUR_BACKGROUND = 'SET_BLUR_BACKGROUND';

export const FETCH_CONNECTION_BY_USER_ID_LOADING = 'FETCH_CONNECTION_BY_USER_ID_LOADING';
export const FETCH_CONNECTION_BY_USER_ID_SUCCESS = 'FETCH_CONNECTION_BY_USER_ID_SUCCESS';
export const FETCH_CONNECTION_BY_USER_ID_ERROR = 'FETCH_CONNECTION_BY_USER_ID_ERROR';

export const CONNECT_FROM_USER_TO_USER_LOADING = 'CONNECT_FROM_USER_TO_USER_LOADING';
export const CONNECT_FROM_USER_TO_USER_SUCCESS = 'CONNECT_FROM_USER_TO_USER_SUCCESS';
export const CONNECT_FROM_USER_TO_USER_ERROR = 'CONNECT_FROM_USER_TO_USER_ERROR';

export const FETCH_NOTIFICATION_BY_USER_ID_LOADING = 'FETCH_NOTIFICATION_BY_USER_ID_LOADING';
export const FETCH_NOTIFICATION_BY_USER_ID_SUCCESS = 'FETCH_NOTIFICATION_BY_USER_ID_SUCCESS';
export const FETCH_NOTIFICATION_BY_USER_ID_ERROR = 'FETCH_NOTIFICATION_BY_USER_ID_ERROR';

export const FETCH_PERSONAL_DETAILS_BY_USER_ID_LOADING =
  'FETCH_PERSONAL_DETAILS_BY_USER_ID_LOADING';
export const FETCH_PERSONAL_DETAILS_BY_USER_ID_SUCCESS =
  'FETCH_PERSONAL_DETAILS_BY_USER_ID_SUCCESS';
export const FETCH_PERSONAL_DETAILS_BY_USER_ID_ERROR = 'FETCH_PERSONAL_DETAILS_BY_USER_ID_ERROR';

export const FETCH_USER_IDS_CONNECTION_BY_USER_ID_LOADING =
  'FETCH_USER_IDS_CONNECTION_BY_USER_ID_LOADING';
export const FETCH_USER_IDS_CONNECTION_BY_USER_ID_SUCCESS =
  'FETCH_USER_IDS_CONNECTION_BY_USER_ID_SUCCESS';
export const FETCH_USER_IDS_CONNECTION_BY_USER_ID_ERROR =
  'FETCH_USER_IDS_CONNECTION_BY_USER_ID_ERROR';

export const FETCH_USERIDS_NOTIFICATIONS_BY_USER_ID_LOADING =
  'FETCH_USERIDS_NOTIFICATIONS_BY_USER_ID_LOADING';
export const FETCH_USERIDS_NOTIFICATIONS_BY_USER_ID_SUCCESS =
  'FETCH_USERIDS_NOTIFICATIONS_BY_USER_ID_SUCCESS';
export const FETCH_USERIDS_NOTIFICATIONS_BY_USER_ID_ERROR =
  'FETCH_USERIDS_NOTIFICATIONS_BY_USER_ID_ERROR';
